### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by johnbianchi** [NetworkedAssets/git4c#9]
I just installed this plugin after your code commit to v1.4.0 on confluence v6.4.0.  
While adding a get4c singlefile macro the edit showed a README.md with markdown as a preview but there was a "Internal Server Error" red block and I could not save the macro.

I removed 1.4.0 and I downloaded 1.3.0 from the marketplace and uploaded to the server and it works just fine.

Not sure if this is the matching log entry to the 1.4.0 errors:
2018-01-19 17:49:24,691 WARN [pool-1758-thread-2] [delivery.executor.monitoring.BackendTimer$Stopwatch] warn ACTION=GetRepositoryUsagesForUserQuery, TRANSACTION=9fe3948c-268a-4b88-8d67-148629453bbc, MESSAGE= Error during processing: com.atlassian.activeobjects.internal.ActiveObjectsInitException: bundle [com.networkedassets.git4c.confluence-plugin] - CompletionException: com.atlassian.activeobjects.internal.ActiveObjectsInitException: bundle [com.networkedassets.git4c.confluence-plugin] at java.util.concurrent.CompletableFuture:273

**Comment by johnbianchi** [comment]
2018-01-19 19:27:09,421 ERROR [pool-1870-thread-2] [delivery.executor.monitoring.BackendTimer$Stopwatch] stopAndLog ACTION=GetExtractionDataByDocumentationsMacroIdQuery, TRANSACTION=cd81710b-1fff-4ce3-8538-d4f1c1bdbb9b, MESSAGE= Error during processing: Unknown extraction data type: class com.networkedassets.git4c.core.datastore.extractors.EmptyExtractor
 -- referer: https://confluence.someplace.com/pages/resumedraft.action?draftId=20906231&draftShareId=d39dc28d-1a7a-4f87-81e7-5b307abfe210 | url: /rest/doc/1.0/documentation/settings/repository/predefine/force | traceId: dc08dde0aa867abc | userName: john.bianchi@someplace.com
java.lang.RuntimeException: Unknown extraction data type: class com.networkedassets.git4c.core.datastore.extractors.EmptyExtractor
        at com.networkedassets.git4c.core.GetExtractionDataByDocumentationsMacroIdUseCase.convertExtractorDataToOutbound(GetExtractionDataByDocumentationsMacroIdUseCase.kt:40)
        at com.networkedassets.git4c.core.GetExtractionDataByDocumentationsMacroIdUseCase.access$convertExtractorDataToOutbound(GetExtractionDataByDocumentationsMacroIdUseCase.kt:17)
        at com.networkedassets.git4c.core.GetExtractionDataByDocumentationsMacroIdUseCase$execute$1.invoke(GetExtractionDataByDocumentationsMacroIdUseCase.kt:28)
        at com.networkedassets.git4c.core.GetExtractionDataByDocumentationsMacroIdUseCase$execute$1.invoke(GetExtractionDataByDocumentationsMacroIdUseCase.kt:17)
        at com.github.kittinunf.result.Result$Companion.of(Result.kt:107)
        at com.networkedassets.git4c.core.GetExtractionDataByDocumentationsMacroIdUseCase.execute(GetExtractionDataByDocumentationsMacroIdUseCase.kt:28)
        at com.networkedassets.git4c.core.GetExtractionDataByDocumentationsMacroIdUseCase.execute(GetExtractionDataByDocumentationsMacroIdUseCase.kt:17)
        at com.networkedassets.git4c.delivery.executor.UseCasesExecutor.executeRequest(UseCasesExecutor.kt:22)
        at com.networkedassets.git4c.delivery.executor.LocalGateway$sendToExecution$1.get(LocalGateway.kt:31)
        at com.networkedassets.git4c.delivery.executor.LocalGateway$sendToExecution$1.get(LocalGateway.kt:18)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I'm not sure if these are the errors tied to the macro not working, let me know if I should look for anything else in the logs

**Comment by bartoszbednarekna** [comment]
Hi, thank you for your ticket and sorry for a delay. We will try to reproduce this situation and check it. We will give an answer as soon as possible in nearest time.

**Comment by bartoszbednarekna** [comment]
As for your second log: "java.lang.RuntimeException: Unknown extraction data type: class com.networkedassets.git4c.core.datastore.extractors.EmptyExtractor" it should be fixed in 1.4.0 release and has no affect to working of plugin. 

As for the first exception: after upgrade from 1.3.0 to 1.4.0 it seems that Confluence has some problems with internal "cache" or datatabase structure upgrage. We are checking the possible solutions and give you know back with answer.

**Comment by bartoszbednarekna** [comment]
Your problem seems to be a problem with Confluence database or cache itself. 
Can you add more details how does it happen? 
Is this situation only after plugin update?

Your confluence plugin cache seems to be corrupted. 

Please try the solution described in here: 
https://confluence.atlassian.com/confkb/how-to-clear-confluence-plugins-cache-297664846.html

Similar problem for another plugin is described also in here: 
https://jira.atlassian.com/browse/CONFSERVER-32046?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by bartoszbednarek** [comment]
Hello, did you manage to solve a problem? 
We have additional question: what database are you using? Is it PostgreSql?
